/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  safelist: [
    "print-a6-sheet",
    "print-bill-sheet",
    "print-bill-header",
    "print-bill-section-head",
    "print-bill-table-wrap",
    "print-bill-number",
    "print-bill-th",
    "print-bill-kv-strip",
    "print-bill-closing-table",
    "print-bill-closing-section",
    "text-right",
    "text-left",
    "flex-row",
    "flex-row-reverse",
    "grid-cols-2",
    "grid-cols-3",
    "grid-cols-4",
    "[direction:ltr]",
    "[unicode-bidi:embed]",
    "bg-slate-50/40",
    "bg-blue-50/70",
    "border-blue-500",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: { sans: ["Inter", "system-ui", "sans-serif"] },
      colors: {
        primary: {
          50: "#FFF7E6",
          100: "#FDEBC4",
          200: "#F7D89B",
          300: "#F2C56B",
          400: "#E8AD3C",
          500: "#D39B2E",
          600: "#C08B24",
          700: "#B8831C",
          800: "#8E6612",
          900: "#694A0B",
        },
      },
    },
  },
  plugins: [],
};
