-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "billHeaderTextSize" DOUBLE PRECISION NOT NULL DEFAULT 14;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "billBodyTextSize" DOUBLE PRECISION NOT NULL DEFAULT 10.5;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "billAmountTextSize" DOUBLE PRECISION NOT NULL DEFAULT 11.5;
