import { Router } from "express";
import * as ctrl from "../controllers/box.controller.js";
import { authenticate, authorizeAnyPermission, authorizePermission } from "../middleware/auth.middleware.js";
import { PERMISSIONS } from "../lib/permissions.js";
const router = Router();
router.use(authenticate);
router.get("/", authorizeAnyPermission(PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.ORDERS_CREATE, PERMISSIONS.SETTINGS_VIEW), ctrl.getAll);
router.get("/:id", authorizeAnyPermission(PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.ORDERS_CREATE, PERMISSIONS.SETTINGS_VIEW), ctrl.getOne);
router.post("/", authorizePermission(PERMISSIONS.INVENTORY_CATEGORIES_MANAGE), ctrl.create);
router.put("/:id", authorizePermission(PERMISSIONS.INVENTORY_CATEGORIES_MANAGE), ctrl.update);
router.delete("/:id", authorizePermission(PERMISSIONS.INVENTORY_CATEGORIES_MANAGE), ctrl.remove);
router.post("/:id/assign", authorizePermission(PERMISSIONS.ORDERS_EDIT), ctrl.assignOrder);
export default router;
