ALTER TABLE "Outfit"
ADD COLUMN IF NOT EXISTS "doubleSidePocket" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ReadyMadeOrder"
ADD COLUMN IF NOT EXISTS "doubleSidePocket" BOOLEAN NOT NULL DEFAULT false;
