export const MEASUREMENT_FIELDS = {
  OUTFIT: [
    ["height", "height"],
    ["shoulder", "shoulder"],
    ["sleeve", "sleeve"],
    ["neck", "neck"],
    ["chest", "chest"],
    ["armpit", "armpit"],
    ["waist", "waist"],
    ["skirt", "skirt"],
    ["tenban", "tenban"],
    ["pantLeg", "pantLeg"],
    ["arm", "arm"],
    ["calf", "calf"],
  ],
  WASKAT: [
    ["height", "height"],
    ["shoulder", "shoulder"],
    ["neck", "neck"],
    ["chest", "chest"],
    ["waist", "waist"],
    ["sorain", "sorain"],
  ],
  KORTY: [
    ["height", "height"],
    ["arm", "arm"],
    ["shoulder", "shoulder"],
    ["neck", "neck"],
    ["sleeve", "sleeve"],
    ["patlonHeight", "patlonHeight"],
    ["kamerPatlon", "kamerPatlon"],
    ["doroBaghlePatlon", "doroBaghlePatlon"],
    ["waist", "waist"],
    ["sorainPatlon", "sorainPatlon"],
    ["sorain", "sorain"],
    ["patPatlon", "patPatlon"],
    ["pachaPatlon", "pachaPatlon"],
  ],
  YAKHANQAQ: [
    ["height", "height"],
    ["sleeve", "sleeve"],
    ["shoulder", "shoulder"],
    ["neck", "neck"],
    ["armpit", "armpit"],
    ["sorain", "sorain"],
    ["chest", "chest"],
  ],
  READY_MADE: [
    ["height", "height"],
    ["chest", "chest"],
    ["waist", "waist"],
    ["shoulder", "shoulder"],
    ["sleeve", "sleeve"],
    ["neck", "neck"],
    ["armpit", "armpit"],
    ["skirt", "skirt"],
    ["tenban", "tenban"],
    ["pantLeg", "pantLeg"],
    ["arm", "arm"],
    ["calf", "calf"],
    ["sorain", "sorain"],
  ],
};

export const STYLE_FIELDS = {
  OUTFIT: [
    ["neckStyle", "neck", "neckoutfit"],
    ["sleeveStyle", "sleeve", "astin"],
    ["sleeveSize", "sleeveSize", null],
    ["skirtStyle", "skirt", "daman"],
    ["outfitDesign", "design", "tenbanship"],
    ["outfitStyle", "style", "outfitdesign"],
    ["buttonStyle", "button", "buttonship"],
    ["pantStyle", "pant", "patyship"],
  ],
  WASKAT: [
    ["neckStyle", "neck", "neckwaskat"],
    ["shoulderState", "shoulderState", "shoulderstate"],
    ["waskatStyle", "style", "__textarea"],
  ],
  KORTY: [["style", "style", "__textarea"]],
  YAKHANQAQ: [
    ["neckStyle", "neck", "yakhanqaqneck"],
    ["sleeveStyle", "sleeve", "yakhanqaqsleeve"],
    ["sleeveSize", "sleeveSize", null],
    ["skirtStyle", "skirt", "yakhanqaqskirt"],
    ["yakhanQaqDesign", "yakhanQaqDesign", "yakhanqaqdesign"],
    ["buttonStyle", "button", "yakhanqaqbutton"],
    ["pantStyle", "pant", "yakhanqaqpant"],
  ],
  READY_MADE: [["additionalNotes", "additionalNotes", "__textarea"]],
};

export const POCKET_FIELDS = {
  OUTFIT: [
    ["frontPocket", "frontPocket"],
    ["sidePocket", "sidePocket"],
    ["underPocket", "underPocket"],
  ],
  YAKHANQAQ: [["frontPocket", "frontPocket"]],
};
